### ISSUE TITLE
Logger name not visible in default message format

### ISSUE THREAD

**Issue by locriacyber** [onjara/optic#4]

**Comment by locriacyber** [comment]
I mean the logger name isn't shown in logged messages with default message format, with a logger like `new Logger("abc")`.

**Comment by cknight** [comment]
Logger names are somewhat niche and so aren't output by default.  However, you can easily setup your console stream to output this.  Here's how:
```typescript
const logger = new Logger();
const consoleStream = new ConsoleStream().withFormat(
  new TokenReplacer().withColor().withFormat(
    "{logger}: {dateTime} {level} {msg} {metadata}",
  ),
);
logger.addStream(consoleStream);

logger.info("hello world");
```
Outputs:
`default: 2022-04-09T20:17:42.373Z Info     hello world `
