### ISSUE TITLE
Log levels names are capitalized

### ISSUE THREAD

**Issue by denizdogan** [onjara/optic#5]
This one caught me off guard, and sometimes still does. Why is it e.g. `Trace` and not `trace`? Is it a bug or intentional?

```console
OPTIC_MIN_LEVEL=trace  # doesn't work!
OPTIC_MIN_LEVEL=Trace  # works!
```

Could we normalize the level names to lowercase?

**Comment by cknight** [comment]
Thanks for the feedback.  There was no special reason to enforce this, so I've added the ability for those inputs to be case insensitive.   Fixed in 11303da69437a2ca5ad83cdfa1305c6499fe5c66. Now available in release 1.3.6.
